project_id = "eliikspzeynkndyygquw"

[functions.scan-receipt]
verify_jwt = false

[functions.scan-product]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.basiq-connect]
verify_jwt = false

[functions.basiq-sync]
verify_jwt = false
